services:
  auth-db:
    container_name: auth_database
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=auth_password123
      - POSTGRES_DB=auth_db
